### ISSUE TITLE
vkconfig "hangs" on macOS 

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1466]
This has been discussed already on chat, but adding an issue just for tracking.

On macOS, when vkConfig is uncovered, it takes a few seconds to become responsive and shows the beachball/wait icon.

**Comment by christophe-lunarg** [comment]
This issue should be fixed with https://github.com/LunarG/VulkanTools/pull/1463.
It doesn't reproduce for me anymore on macOS

**Comment by richard-lunarg** [comment]
I'm also still seeing this today. Investigating to see if I can't figure out why as well.

**Comment by richard-lunarg** [comment]
Gone again. Could have been debug builds on the M1 Mac.
