### ISSUE TITLE
APIDump Settings missing Console Output

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1469]
The default API dump configuration has "Output to File" unchecked and output goes to the log window. If you create a new config and add API dump layer, Output to File is set, and the default folder is next to the executable, which on macOS is inside the app bundle.

a. You can't write there.
b. There is no way to restore this to the console. There was recently a "Console Output Preset", but now it's gone.

**Comment by richard-lunarg** [comment]
This is probably why I kept running into the issue where the API dump "wasn't working". I'd experiment, change the defaults, and it would not go back to writing to the console log.

**Comment by christophe-lunarg** [comment]
This issue is fixed but not that you need to update the API Dump JSON file to get the fix.

**Comment by richard-lunarg** [comment]
@christophe-lunarg Will just a "Reset to Default" do this? I'm testing your 176 branch, and I'm still seeing the problem (but all I've done is rebuild vkConfig).

**Comment by christophe-lunarg** [comment]
Nope, you need to update the API dump layer too.
