### ISSUE TITLE
VIA PnP Configuration Manager API

### ISSUE THREAD

**Issue by dor666** [LunarG/VulkanTools#358]
Currently Via on Windows, searches for Drivers using _SOFTWARE\Khronos\Vulkan\Drivers_ registry entry:
https://github.com/LunarG/VulkanTools/blob/b24301604e94597c4714da3d36741552b7f9d491/via/via.cpp#L1780

Since drivers should no longer use HKLM/SOFTWARE tree,  there was a change in documentation on how to obtain the same info in new way: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/eb2701cd70d3b95801052e42dc51b3e680edd72b#diff-d83f5e9b803140d2ad7db4c46b977601

Via was not updated accordingly and only searches in _SOFTWARE\Khronos\Vulkan\Drivers_.

**Comment by MarkY-LunarG** [comment]
What version of VIA are you using?  Are you building it or using it from an SDK?

VIA should look for drivers in both the old and new locations starting with the 1.0.65.0 SDK drop we released.  The code in question is in [via.cpp](https://github.com/LunarG/VulkanTools/blob/master/via/via.cpp) and the function is called ReadDriverSpecificRegistry.  My understanding was this was working fine.  Please let me know if it is not.

**Comment by dor666** [comment]
Hi Mark,
Thanks for answer. I think you're right and I used older version. I will double check it and let you know.

**Comment by dor666** [comment]
Hmmm...
It looks like the issue persists on 1.0.65.0

Z:\Tools\VulkanSDK\1.0.65.0\Bin>via.exe
ERROR: Failed to find Vulkan Driver JSON in registry.

It may also be a problem in my driver. I will compile latest via tomorrow and check it .

**Comment by MarkY-LunarG** [comment]
I'm adding the current Vulkan Loader owner (@lenny-lunarg) to help with this for now since he might have some insight to the problem.

Are you running AMD, Intel or Nvidia?

If you have a current VIA output, feel free to attach it too, that will help us know the basics of your system if nothing else.

**Comment by dor666** [comment]
I'm using Intel 15.50 driver https://downloadcenter.intel.com/download/27266/Graphics-Intel-Graphics-Driver-for-Windows-15-60-
I'm using Skylake but platform should not affect the issue.

If this is not a vanilla fresh OS, you have to backup/remove [HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers] as previous Intel or Nvidia drivers puts entries there and do not delete it on driver uninstall.

I haven't stepped through the code, but I guess that VIA assumes that  [HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers] is present (even with no entries inside)

**Comment by dor666** [comment]
There are couple of bugs here:

1.  PrintDriverInfo sets vulkan_driver_reg_key to "DriverName" - for driver specific registry it should be "VulkanDriverName".
2.  ReadDriverSpecificRegistry gets good path (if 1. fix applied) but this is a path to json file, not a reg key. So pushing it to registry_top_hkey, and registry_locations is wrong. As it will be misinterpreted by PrintDriverRegInfo().
3. I was inspecting PrintDriverInfo() only, ReadDriverSpecificRegistry is used in couple more locations in similar way.

**Comment by MarkY-LunarG** [comment]
Ok.  I tried to duplicate the new setup on my machine (this is not an exact test), but I was able to make a number of changes which resolved some of the issues you see.  I've pushed my changes up into the `marky_master_fix_driverspecific_reg` branch, can you try those out?

**Comment by dor666** [comment]
Thanks Mark.
I checked out your branch and it works. Thanks :)

Verified on Intel 15.60 driver.

**Comment by MarkY-LunarG** [comment]
Fixed with PR #361
